version: '3'
services:
        web:
                image: flask_3333_v1
                build: .
                ports:
                        - "3333:3333"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped
